Tag image with the github tag

diff --git a/.github/workflows/docker-build-and-push.yml b/.github/workflows/docker-build-and-push.yml
--- a/.github/workflows/docker-build-and-push.yml
+++ b/.github/workflows/docker-build-and-push.yml
@@ -19,9 +19,14 @@ jobs:
       - name: Extract Git Tag
         id: extract_tag
         run: |
-          TAG=${GITHUB_REF#refs/tags/}
-          echo "TAG=$TAG"
-          echo "tag=$TAG" >> $GITHUB_ENV
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+            TAG=${GITHUB_REF#refs/tags/}
+            echo "TAG=$TAG"
+            echo "tag=$TAG" >> $GITHUB_ENV
+          else
+            echo "No valid Git tag found."
+            exit 1  # Fail the workflow if no tag is found
+          fi
 
       # Step 3: Log in to Docker Hub
       - name: Log in to Docker Hub
