Push new image version : 1.5.7

diff --git a/.github/workflows/docker-build-and-push.yml b/.github/workflows/docker-build-and-push.yml
--- a/.github/workflows/docker-build-and-push.yml
+++ b/.github/workflows/docker-build-and-push.yml
@@ -15,28 +15,34 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      # Step 2: Log in to Docker Hub
+      # Step 2: Read the version from the VERSION file
+      - name: Read version from VERSION file
+        id: get_version
+        run: |
+          if [ ! -f VERSION ]; then
+            echo "VERSION file is missing. Exiting..."
+            exit 1
+          fi
+          version=$(cat VERSION)
+          echo "Version: $version"
+          echo "version=$version" >> $GITHUB_ENV
+
+      # Step 3: Log in to Docker Hub
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      # Step 3: Set up Docker Buildx (for multi-platform builds)
+      # Step 4: Set up Docker Buildx (for multi-platform builds)
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-
-      # Step 4: Build and push the Docker image
+      # Step 5: Build and push the Docker image
       - name: Build and Push Docker Image
         uses: docker/build-push-action@v4
         with:
           push: true  # Push the image to Docker Hub
           tags: |
             muhohoweb/course-image:latest
-            muhohoweb/course-image:latest
-
-      # Step 5: Verify the Docker image
-#      - name: Image Digest
-#        run:
-#          echo "Docker image pushed with digest: ${{ steps.build-and-push.outputs.digest }}"
+            muhohoweb/course-image:${{ env.version }}
